load("@fbcode_macros//build_defs:python_library.bzl", "python_library")

oncall("fill in oncall here @nocommit")

python_library(
    name = "features_utils",
    srcs = ["features_utils.py"],
    labels = ["autodeps2_generated"],
    deps = [
        "fbsource//third-party/pypi/einops:einops",
        "fbsource//third-party/pypi/open-clip-torch:open-clip-torch",
        "fbsource//third-party/pypi/torch:torch",
        "//pytorch/vision:torchvision",
        "//scripts/feiyanzhou/wavflow_project/feature_extract/ext/synchformer:__init__",
    ],
)
