load("@fbcode_macros//build_defs:python_binary.bzl", "python_binary")
load("@fbcode_macros//build_defs:python_library.bzl", "python_library")

oncall("fill in oncall here @nocommit")

python_library(
    name = "__init__",
    srcs = ["__init__.py"],
    labels = ["autodeps2_generated"],
)

python_binary(
    name = "synchformer",
    srcs = ["synchformer.py"],
    labels = ["autodeps2_generated"],
    main_module = "scripts.feiyanzhou.wavflow_project.feature_extract.ext.synchformer.synchformer",
    deps = [
        "fbsource//third-party/pypi/torch:torch",
    ],
)

python_library(
    name = "motionformer",
    srcs = ["motionformer.py"],
    labels = ["autodeps2_generated"],
    deps = [
        "fbsource//third-party/pypi/einops:einops",
        "fbsource//third-party/pypi/omegaconf:omegaconf",
        "fbsource//third-party/pypi/timm:timm",
        "fbsource//third-party/pypi/torch:torch",
    ],
)

python_library(
    name = "utils",
    srcs = ["utils.py"],
    labels = ["autodeps2_generated"],
    deps = [
        "fbsource//third-party/pypi/requests:requests",
        "fbsource//third-party/pypi/tqdm:tqdm",
    ],
)

python_library(
    name = "video_model_builder",
    srcs = ["video_model_builder.py"],
    labels = ["autodeps2_generated"],
    deps = [
        "fbsource//third-party/pypi/timm:timm",
        "fbsource//third-party/pypi/torch:torch",
        ":__init__",
    ],
)

python_library(
    name = "vit_helper",
    srcs = ["vit_helper.py"],
    labels = ["autodeps2_generated"],
    deps = [
        "fbsource//third-party/pypi/einops:einops",
        "fbsource//third-party/pypi/timm:timm",
        "fbsource//third-party/pypi/torch:torch",
    ],
)
